version: '3'
services:
  mongo:
    image: mongo
    restart: no


  jguweka:
    image: snowdwq/jguweka:OAS3
    restart: no
    links:
      - "mongo:mongodb"
    ports:
      - "8849"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - jguweka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - jguweka
    ports:
      - "80:80"



